# Question 1

# Jupyter Notebook Basics

## Working with Markdown and Code Cells

### Markdown Formatting Examples
- **Bold Text**
- *Italic Text*
- `Inline Code Example`
- ~~Strikethrough Text~~

### List
1. Ordered Item 1
2. Ordered Item 2

- Unordered Item 1
- Unordered Item 2

### Code Example
Below is a simple Python Code.

In [1]:
course_name = "Data Analytics and Optimization"
course_code = "ECE3403"

In [2]:
print(f"Let's start first section in {course_code} - {course_name}")

Let's start first section in ECE3403 - Data Analytics and Optimization



---

# Question 2

**Create a 3 × 3 NumPy ndarray containing consecutive integers from 1 to 9 (inclusive)**

`np.arange()` returns evenly spaced values within a given interval.
- `arange(start_val, stop_val, step_size)`
    - `np.arange(N)` will create a rank 1 ndarray with consecutive integers between `0` and `N - 1`
    - `np.arange(start,stop)` will create a rank 1 ndarray with evenly spaced values within the half-open interval `[start, stop)`. This means the evenly spaced numbers will include `start` but exclude `stop`.
    - `np.arange(start,stop,step)` will create a rank 1 ndarray with evenly spaced values within the half-open interval `[start, stop)` with `step` being the distance between two adjacent values.

In [3]:
import numpy as np

In [4]:
X = np.arange(1, 10)

In [5]:
X

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

`np.reshape()` gives a new shape to an array without changing its data.
- It is important to note that the new_shape should be compatible with the number of elements in the given ndarray.

In [6]:
X = X.reshape(3,3)

In [7]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1. Print the following properties of the array (Data type, Shape, Size).

In [8]:
X.dtype

dtype('int64')

In [9]:
X.shape

(3, 3)

In [10]:
X.size

9

## 2. Retrieve the element in the second row, third column.

In [11]:
print(X[1][2])
print(X[1,2])

6
6

## 3. Update the entire first row to [10, 11, 12]

In [12]:
X[0] = [10, 11, 12]
X

array([[10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

## 4. Delete the second row.
`np.delete(ndarray, elements, axis)`
- `axis = 0` is used to select *rows*

In [13]:
X = np.delete(X, 1, axis=0)
X

array([[10, 11, 12],
       [ 7,  8,  9]])

## 5. Delete the last column.
`np.delete(ndarray, elements, axis)`
- `axis = 1` is used to select *columns*

In [14]:
X = np.delete(X, -1, axis=1)
X

array([[10, 11],
       [ 7,  8]])

## 6. Append the row [13, 14]
`np.append(ndarray, elements, axis)`
- `axis=0` is used to select *rows*

**Notice that when appending rows or columns to rank 2 ndarrays the rows or columns must have the correct shape, so as to match the shape of the rank 2 ndarray.**

In [15]:
X = np.append(X, [[13,14]], axis=0)
X

array([[10, 11],
       [ 7,  8],
       [13, 14]])

## 7. Append the column [1, 2, 3]
`np.append(ndarray, elements, axis)`
- `axis=1` is used to select *columns*

**Notice that when appending rows or columns to rank 2 ndarrays the rows or columns must have the correct shape, so as to match the shape of the rank 2 ndarray.**

In [16]:
X = np.append(X, [[1],[2],[3]], axis=1)
X

array([[10, 11,  1],
       [ 7,  8,  2],
       [13, 14,  3]])

## 8. Insert a new column [20, 30, 40] as the second column.
`np.insert(ndarray, index, elements, axis)`

In [17]:
X = np.insert(X, 1, [20, 30, 40], axis=1)
X

array([[10, 20, 11,  1],
       [ 7, 30,  8,  2],
       [13, 40, 14,  3]])

## 9. Use Boolean indexing to extract only the odd numbers from the array.

In [18]:
odd_numbers = X[X % 2 != 0]
odd_numbers

array([11,  1,  7, 13,  3])

## 10. Create another 2D array **arr2D_2 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])**, then vertically stack both of the arrays.

- `numpy.hstack(sequence_of_ndarray)`: It returns a stacked array formed by stacking the given arrays in sequence horizontally ***(column-wise)***
- `numpy.vstack(sequence_of_ndarray)`: It returns a stacked array formed by stacking the given arrays, will be at least 2-D, in sequence vertically ***(row-wise)***

**It is important to note that in order to stack ndarrays, the shape of the ndarrays must match.**

In [19]:
arr2D_2 = np.array([
    [10, 20, 30, 40],
     [50, 60, 70, 80]
    ])

In [20]:
X = np.vstack([X, arr2D_2])
X

array([[10, 20, 11,  1],
       [ 7, 30,  8,  2],
       [13, 40, 14,  3],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

## 11. Create a copy of the original array, then slice this copy to extract the first two rows and last two columns.

### **Slicing**
1. `ndarray[start:end]`: is used to select elements between the **'start'** and **'end'** indices.
2. `ndarray[start:]`: is used to select all elements from the **'start'** index till the last index.
3. `ndarray[:end]`: is used to select all elements from the first index till the **'end'** index.

**Note:** in methods one and three, the **'end'** index is excluded.

In [21]:
arr2D_copy = X.copy()
arr2D_copy

array([[10, 20, 11,  1],
       [ 7, 30,  8,  2],
       [13, 40, 14,  3],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [22]:
                    # [row, column]
arr2D_copy = arr2D_copy[:2, -2:]
arr2D_copy

array([[11,  1],
       [ 8,  2]])

## 12. Find and display the unique elements in the original array.

In [23]:
unique_elements = np.unique(X)
unique_elements

array([ 1,  2,  3,  7,  8, 10, 11, 13, 14, 20, 30, 40, 50, 60, 70, 80])



---

# Question 3

![Alt text](https://www.w3resource.com/w3r_images/pandas-data-structure.svg)

In [24]:
import pandas as pd

In [25]:
books = ['Great Expectations', 'Of Mice and Men', 'Romeo and Juliet', 'The Time Machine', 'Alice in Wonderland']
authors = ['Charles Dickens', 'John Steinbeck', 'William Shakespeare', 'H. G. Wells', 'Lewis Carroll']

# User ratings (aligned with the book titles above)
user_1 = pd.Series([3.2, 4.0, 2.5])
user_2 = pd.Series([5.0, 1.3, 4.0, 3.8])
user_3 = pd.Series([2.0, 2.3, 3.2, 4.0])
user_4 = pd.Series([4.0, 3.5, 4.0, 5.0, 4.2])

## 1. Create a Pandas Series from **books** and **authors** list.

In [26]:
books_series = pd.Series(books)
authors_series = pd.Series(authors)

## 2. Create a dictionary using the given data where:
- The keys are **'Author'**, **'Book Title'**, **'User 1'**, **'User 2'**, **'User 3'**, and **'User 4'**.
- The values are the corresponding Series objects.

In [27]:
dat = {'Author': authors_series,
       'Book Title': books_series,
       'User 1': user_1,
       'User 2': user_2,
       'User 3': user_3,
       'User 4': user_4}

## 3. Create a Pandas DataFrame from the dictionary, allowing Pandas to automatically assign numerical row indices.

In [28]:
book_ratings = pd.DataFrame(dat)

In [29]:
book_ratings

                Author           Book Title  User 1  User 2  User 3  User 4
0      Charles Dickens   Great Expectations     3.2     5.0     2.0     4.0
1       John Steinbeck      Of Mice and Men     4.0     1.3     2.3     3.5
2  William Shakespeare     Romeo and Juliet     2.5     4.0     3.2     4.0
3          H. G. Wells     The Time Machine     NaN     3.8     4.0     5.0
4        Lewis Carroll  Alice in Wonderland     NaN     NaN     NaN     4.2

## 4. Print key attributes of the DataFrame: The **shape**, **number of dimensions**, **total elements**, **values**, **index**, and **column names**.

In [30]:
print("Shape: ", book_ratings.shape)
print("Number of Dimensions: ", book_ratings.ndim)
print("Total elements: ", book_ratings.size)
print("The data: ", book_ratings.values)
print("The index: ", book_ratings.index)
print("The column index in book ratings: ", book_ratings.columns)

Shape:  (5, 6)
Number of Dimensions:  2
Total elements:  30
The data:  [['Charles Dickens' 'Great Expectations' 3.2 5.0 2.0 4.0]
 ['John Steinbeck' 'Of Mice and Men' 4.0 1.3 2.3 3.5]
 ['William Shakespeare' 'Romeo and Juliet' 2.5 4.0 3.2 4.0]
 ['H. G. Wells' 'The Time Machine' nan 3.8 4.0 5.0]
 ['Lewis Carroll' 'Alice in Wonderland' nan nan nan 4.2]]
The index:  RangeIndex(start=0, stop=5, step=1)
The column index in book ratings:  Index(['Author', 'Book Title', 'User 1', 'User 2', 'User 3', 'User 4'], dtype='object')

## 5. Display only the **'Book Title'** and **'Author'** columns.

In [31]:
print(book_ratings[['Book Title', 'Author']])

            Book Title               Author
0   Great Expectations      Charles Dickens
1      Of Mice and Men       John Steinbeck
2     Romeo and Juliet  William Shakespeare
3     The Time Machine          H. G. Wells
4  Alice in Wonderland        Lewis Carroll

## 6. Display the first three rows of the DataFrame.

In [32]:
print(book_ratings[:3])

                Author          Book Title  User 1  User 2  User 3  User 4
0      Charles Dickens  Great Expectations     3.2     5.0     2.0     4.0
1       John Steinbeck     Of Mice and Men     4.0     1.3     2.3     3.5
2  William Shakespeare    Romeo and Juliet     2.5     4.0     3.2     4.0

In [33]:
book_ratings.head(3)

                Author          Book Title  User 1  User 2  User 3  User 4
0      Charles Dickens  Great Expectations     3.2     5.0     2.0     4.0
1       John Steinbeck     Of Mice and Men     4.0     1.3     2.3     3.5
2  William Shakespeare    Romeo and Juliet     2.5     4.0     3.2     4.0

## 7. Insert a new column **'Average Rating'** that represents the average rating across all users for each book.

In [34]:
book_ratings['Average Rating'] = book_ratings[['User 1', 'User 2', 'User 3', 'User 4']].mean(axis=1)

In [35]:
book_ratings

,Author,Book Title,User 1,User 2,User 3,User 4,Average Rating
0,Charles Dickens,Great Expectations,3.2,5.0,2.0,4.0,3.550000
1,John Steinbeck,Of Mice and Men,4.0,1.3,2.3,3.5,2.775000
2,William Shakespeare,Romeo and Juliet,2.5,4.0,3.2,4.0,3.425000
3,H. G. Wells,The Time Machine,NaN,3.8,4.0,5.0,4.266667
4,Lewis Carroll,Alice in Wonderland,NaN,NaN,NaN,4.2,4.200000

## 8. Append a new row for the book **"Pride and Prejudice"** by **"Jane Austen"**, with ratings **[4.5, 4.0, 3.8, 4.9]**

In [36]:
new_row = pd.DataFrame([{'Author': "Jane Austen",
       'Book Title': "Pride and Prejudice",
       'User 1': 4.5,
       'User 2': 4.0,
       'User 3': 3.8,
       'User 4': 4.9}])

In [37]:
book_ratings = pd.concat([book_ratings, new_row], ignore_index=True)

In [38]:
book_ratings

,Author,Book Title,User 1,User 2,User 3,User 4,Average Rating
0,Charles Dickens,Great Expectations,3.2,5.0,2.0,4.0,3.550000
1,John Steinbeck,Of Mice and Men,4.0,1.3,2.3,3.5,2.775000
2,William Shakespeare,Romeo and Juliet,2.5,4.0,3.2,4.0,3.425000
3,H. G. Wells,The Time Machine,NaN,3.8,4.0,5.0,4.266667
4,Lewis Carroll,Alice in Wonderland,NaN,NaN,NaN,4.2,4.200000
5,Jane Austen,Pride and Prejudice,4.5,4.0,3.8,4.9,NaN

## 9. Rename the column **'Book Title'** to **'Title'**

In [39]:
book_ratings.rename(columns={'Book Title': 'Title'}, inplace=True)

In [40]:
book_ratings

,Author,Title,User 1,User 2,User 3,User 4,Average Rating
0,Charles Dickens,Great Expectations,3.2,5.0,2.0,4.0,3.550000
1,John Steinbeck,Of Mice and Men,4.0,1.3,2.3,3.5,2.775000
2,William Shakespeare,Romeo and Juliet,2.5,4.0,3.2,4.0,3.425000
3,H. G. Wells,The Time Machine,NaN,3.8,4.0,5.0,4.266667
4,Lewis Carroll,Alice in Wonderland,NaN,NaN,NaN,4.2,4.200000
5,Jane Austen,Pride and Prejudice,4.5,4.0,3.8,4.9,NaN